name: Test
on: { push: , pull_request: }

jobs:
  test:
    strategy: { matrix: { node-version: [ ^18.20, ^20.10, ">=22" ] } }
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4 }

    - name: Setup Node.js ${{ matrix.node-version }} environment
      uses: actions/setup-node@v4
      with: { node-version: "${{ matrix.node-version }}" }

    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { version: ^9, run_install: true } }
    - run: pnpm package
    - run: pnpm lint
